
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue May 03 01:57:02 CDT 2022
//----------------------------------------------------

package fes.aragon.compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 4;
  public static final int TRUE = 6;
  public static final int EOF = 0;
  public static final int ASIG = 10;
  public static final int FALSE = 7;
  public static final int ID = 11;
  public static final int error = 1;
  public static final int RPAREN = 9;
  public static final int NOT = 5;
  public static final int PUNTOYCOMA = 2;
  public static final int LPAREN = 8;
  public static final int OR = 3;
}

