/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fes.aragon.codigo;
//demostracion de la clase JLabel
import java.awt.Container;
import java.awt.FlowLayout;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
/**
 *
 * @author Admin01
 */
public class JFrame1 extends JFrame {
private JLabel etiqueta1, etiqueta2, etiqueta3;

    //configurar la GUI
    /**
     * Creates new form JFrame1
     */
    public JFrame1() {
        super("Prueba de JLabel");
            
            //Obtener panel de contenido y establecer esquema
            Container contenedor = getContentPane();
            contenedor.setLayout (new FlowLayout());
            
            //constructor de JLabel con un argumento cadena
            etiqueta1=new JLabel("Etiqueta con texto");
            etiqueta1.setToolTipText("Etiqueta 1");
            contenedor.add(etiqueta1);
            
            //constructor de JLabel con argumentos cadena, Icono y alineacion
            Icon insecto=new ImageIcon("insecto.gif");
            etiqueta2=new JLabel ("Etiqueta con texto e icono", insecto, SwingConstants.LEFT);
            etiqueta2.setToolTipText("Etiqueta 2");
            contenedor.add (etiqueta2);
            
            //constructor de JLabel sin argumentos 
            etiqueta3=new JLabel();
            etiqueta3.setText("etiqueta con icono y texto inferior");
            etiqueta3.setIcon(insecto);
            etiqueta3.setHorizontalTextPosition(SwingConstants.CENTER);
            etiqueta3.setVerticalTextPosition(SwingConstants.BOTTOM);
            etiqueta3.setToolTipText("Etiqueta 3");
            contenedor.add(etiqueta3);
            
            setSize(450, 400);
            setVisible(true);
       
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//fin del constructor
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
   
JFrame1 aplicacion= new JFrame1();
aplicacion.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
