/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fes.aragon.inicio;

import fes.aragon.elementos.Automovil;
import fes.aragon.elementos.Estorbo;
import fes.aragon.elementos.ImagenFondo;
import fes.aragon.elementos.Puntuacion;
import fes.aragon.pantalla.Pantalla;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.Timer;

/**
 *
 * @author Admin01
 */
public class Inicio extends javax.swing.JFrame {
    private int fps=30;
    private Timer tiempo;
    /**
     * Creates new form Inicio
     */
    public Inicio(){
       
        ActionListener accion= new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
            refrescar();    
            }
        };
        this.tiempo = new Timer(10, accion);
        this.tiempo.start();                
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(this);
        this.jPanel1.requestFocusInWindow();
        ImagenFondo fondo2 = ImagenFondo.getImagenFondo();
        fondo2.configuracion(this.jPanel1, "carretera.gif", "nave.gif");
        
        Estorbo estorbo=Estorbo.getEstorbo();
        estorbo.configurar(this.jPanel1,"cono.png" ,"pajaros2.gif");
        
        Automovil automovil=Automovil.getAutomovil();
        automovil.configurar(this.jPanel1, "Lancer.png");
        
        Puntuacion puntuacion= new Puntuacion(jPanel1);
       
        
       
        //Musica musica=new Musica("musicaentrada.mp3");
        //Thread hilo= new Thread(musica);
        //hilo.start();
        
        ((Pantalla) this.jPanel1).getComponente().add(fondo2);
        ((Pantalla) this.jPanel1).getComponente().add(estorbo);
        ((Pantalla) this.jPanel1).getComponente().add(automovil);
        //Se borran los estorbos al inicializar puntuacion
        //((Pantalla) this.jPanel1).getComponente().add(puntuacion);
      
    } 
     private void refrescar(){
        long inicio;
        long transcurrido;
        long espera;
        try {
            inicio= System.nanoTime();
            this.jPanel1.repaint();
            transcurrido=System.nanoTime();
            espera=1000 / fps -(transcurrido=inicio)/1000000;
            espera =(espera<0) ? 0 :espera;
                Thread.sleep(espera);
       } catch (InterruptedException ex) {
           ex.printStackTrace();
       } }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new fes.aragon.pantalla.Pantalla(tiempo);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 524, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
